[Interface]
PrivateKey = yIGYCNNdqy1980F9jYPgnshrJKjpO7kDydRdrB6LeHg=
Address = 10.9.0.2/24

[Peer]
PublicKey = pgnechykAR9j1euGosheDkp3oL6UiPvcPiDR5jvJaC8=
Endpoint = 10.10.10.68:51820
AllowedIPs = 10.9.0.0/24, 10.10.10.0/24
PersistentKeepalive = 25
