[Interface]
PrivateKey = aLY6O2JYtDnEj1N9wT4fJT85J5vjVPrUHI8TlLt4lmo=
Address = 10.9.0.1/24
ListenPort = 51820

[Peer]
PublicKey = QrAvAuTLs8N2qUsogAIvJoeqi9dMPl29EOOwz18DQ3w=
AllowedIPs = 10.9.0.2/32
